name: Build and deploy container
on:
  push:
    branches: [ "okta" ]
permissions:
  id-token: write
  packages: write
  contents: read    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Setup the build environment
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: generate tag
        run: |-
          echo "TAG=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          
      
      
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: source/Dockerfile
          context: source/
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.TAG }}

      - name: get kubernetes configuration
        run: |
          pip3 install -r .github/workflows/requirements.txt
          python3 .github/workflows/load_kubeconfig.py $OKTA_DOMAIN $OKTA_USER $OKTA_PASSWORD $OU_HOST

      - name: patch deployment
        run: |
          kubectl patch deployment run-service -n myapp -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"pause\",\"image\":\"ghcr.io/${{ env.REPO }}:${{ env.TAG }}\"}]}}}}"


